name: Build main.tex

on:
  push:
    branches: [ build ]

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner OS

    steps:
      - uses: actions/checkout@v4  # Checkout your code

      - name: Install texlive-full
        run: sudo apt update && sudo apt install -y texlive-full

      - name: Build Resume
        run: pdflatex main.tex && mv main.pdf resume.pdf

      - name: Upload Resume
        uses: actions/upload-artifact@v4  # Uploads generated PDF as artifact
        with:
          name: resume.pdf
          path: resume.pdf
