name: Build and deploy main.tex

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install texlive-full
        run: sudo apt update && sudo apt install -y texlive-full

      - name: Build Resume
        run: pdflatex main.tex && mv main.pdf resume.pdf

      - name: Upload Resume
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
